# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 04:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habitat_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnCompartment',
            fields=[
                ('burncompartment_id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, srid=2163)),
                ('compartment_set', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'burn_compartment',
            },
        ),
        migrations.CreateModel(
            name='FirebreakLine',
            fields=[
                ('fbkln_id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=2163)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('length_meters', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firebreak_line',
            },
        ),
        migrations.CreateModel(
            name='HabitatEnhancementArea',
            fields=[
                ('habenharea_id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=2163)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habitat_enhancement_area',
            },
        ),
        migrations.CreateModel(
            name='HabitatEnhancementPoint',
            fields=[
                ('habenhpt_id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=2163)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habitat_enhancement_point',
            },
        ),
        migrations.CreateModel(
            name='HabitatEnhancementType',
            fields=[
                ('habenhtype_id', models.IntegerField(primary_key=True, serialize=False)),
                ('habenhtype_cd', models.CharField(blank=True, max_length=3)),
                ('habenhtype_dsc', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'habitat_enhancement_type',
            },
        ),
        migrations.AddField(
            model_name='habitatenhancementpoint',
            name='habenhtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habitat_management.HabitatEnhancementType'),
        ),
        migrations.AddField(
            model_name='habitatenhancementarea',
            name='habenhtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habitat_management.HabitatEnhancementType'),
        ),
    ]
