# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 03:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalPoint',
            fields=[
                ('cultpt_id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=2163)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cultural_point',
            },
        ),
        migrations.CreateModel(
            name='CulturalType',
            fields=[
                ('culttype_id', models.IntegerField(primary_key=True, serialize=False)),
                ('culttype_cd', models.CharField(blank=True, max_length=3)),
                ('culttype_dsc', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'cultural_type',
            },
        ),
        migrations.CreateModel(
            name='RecreationPoint',
            fields=[
                ('recpt_id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=2163)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recreation_point',
            },
        ),
        migrations.CreateModel(
            name='RecreationType',
            fields=[
                ('rectype_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rectype_cd', models.CharField(blank=True, max_length=3)),
                ('rectype_dsc', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'recreation_type',
            },
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('trail_id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=2163)),
                ('trail_name', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('trail_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrailStatusType',
            fields=[
                ('trailstatus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trailstatus_cd', models.CharField(blank=True, max_length=4, null=True)),
                ('trailstatus_dsc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'trail_status_type',
            },
        ),
        migrations.CreateModel(
            name='TrailType',
            fields=[
                ('trailtype_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trailtype_cd', models.CharField(blank=True, max_length=4, null=True)),
                ('trailtype_dsc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'trail_type',
            },
        ),
        migrations.AddField(
            model_name='trail',
            name='trailstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recreation.TrailStatusType'),
        ),
        migrations.AddField(
            model_name='trail',
            name='trailtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recreation.TrailType'),
        ),
        migrations.AddField(
            model_name='recreationpoint',
            name='rectype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recreation.RecreationType'),
        ),
        migrations.AddField(
            model_name='culturalpoint',
            name='culttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recreation.CulturalType'),
        ),
    ]
