# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'recreation', '0002_trail_created_by'), (b'recreation', '0003_auto_20160109_2023'), (b'recreation', '0004_trail_created_by'), (b'recreation', '0005_auto_20160114_1316')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recreation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trail',
            table='trail',
        ),
        migrations.AddField(
            model_name='trail',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trailstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recreation.TrailStatusType', verbose_name=b'Status'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trailtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recreation.TrailType', verbose_name=b'Type'),
        ),
    ]
