ALTER TABLE activity_type RENAME TO activitytype;
ALTER TABLE control_point RENAME TO controlpoint;
ALTER TABLE cultural_point RENAME TO culturalpoint;
ALTER TABLE firebreak_line RENAME TO firebreakline ;
ALTER TABLE habitat_enhancement_area RENAME TO habitatenhancementarea ;
ALTER TABLE habitat_enhancement_point RENAME TO habitatenhancementpoint ;
ALTER TABLE habitat_enhancement_type RENAME TO habitatenhancementtype;
ALTER TABLE harvest_area RENAME TO harvestarea ;
ALTER TABLE harvest_type RENAME TO harvesttype ;
ALTER TABLE land_area RENAME TO landarea ;
ALTER TABLE recreation_point RENAME TO recreationpoint ;
ALTER TABLE recreation_type RENAME TO recreationtype;
ALTER TABLE road_line RENAME TO roadline ;
ALTER TABLE road_type RENAME TO roadtype ;
ALTER TABLE stand_activity RENAME TO standactivity ;
ALTER TABLE stand_area RENAME TO standarea ;
ALTER TABLE stocking_type RENAME TO stockingtype;
ALTER TABLE tree RENAME TO treepoint;
