psql -U postgres -d fsp -h localhost -f ./table_updates/activity_area.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/burncompartment.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/controlpoint.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/culturalpoint.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/firebreakline.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/forestinventorydata.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/forestinventoryplot.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/habitatenhancementarea.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/habitatenhancementpoint.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/hazard.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/landarea.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/plannedactivity.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/recreationpoint.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/roadline.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/smz.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/soiltest.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/soiltestrecommendation.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/standarea.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/standstatus.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/stream.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/trail.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/tree.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/tree_status.sql
psql -U postgres -d fsp -h localhost -f ./table_updates/waterpoint.sql